/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.stu.ordersystem;

public final class R {
    public static final class attr {
    }
    public static final class color {
        public static final int blue=0x7f040006;
        public static final int darkgrey=0x7f040001;
        public static final int green=0x7f040007;
        public static final int grey=0x7f040000;
        public static final int lightblue=0x7f040008;
        public static final int lightgrey=0x7f040003;
        public static final int orange=0x7f04000e;
        public static final int originalred=0x7f04000c;
        public static final int red=0x7f040002;
        public static final int superlightblue=0x7f04000d;
        public static final int tinyred=0x7f04000f;
        public static final int titleblue=0x7f040009;
        public static final int titlecolor=0x7f040005;
        public static final int titlered=0x7f04000b;
        public static final int transparent=0x7f040004;
        public static final int white=0x7f04000a;
    }
    public static final class dimen {
        public static final int NameTextSize=0x7f050004;
        public static final int PriceTextSize=0x7f050005;
        public static final int RankTextSize=0x7f050003;
        public static final int RelativeLayoutHeight=0x7f050002;
        /**  Default screen margins, per the Android Design guidelines. 

         Customize dimensions originally defined in res/values/dimens.xml (such as
         screen margins) for sw720dp devices (e.g. 10" tablets) in landscape here.
    
         */
        public static final int activity_horizontal_margin=0x7f050000;
        public static final int activity_vertical_margin=0x7f050001;
    }
    public static final class drawable {
        public static final int add=0x7f020000;
        public static final int add2=0x7f020001;
        public static final int add3=0x7f020002;
        public static final int add4=0x7f020003;
        public static final int add5=0x7f020004;
        public static final int ball=0x7f020005;
        public static final int beefnoodle=0x7f020006;
        public static final int beefriceflour=0x7f020007;
        public static final int beefsoup=0x7f020008;
        public static final int bottom_bar=0x7f020009;
        public static final int cole=0x7f02000a;
        public static final int deliever=0x7f02000b;
        public static final int drop=0x7f02000c;
        public static final int eastgate=0x7f02000d;
        public static final int emoji=0x7f02000e;
        public static final int ic_add_circle_outline_black_24dp=0x7f02000f;
        public static final int ic_add_shopping_cart_black_24dp=0x7f020010;
        public static final int ic_arrow=0x7f020011;
        public static final int ic_help=0x7f020012;
        public static final int ic_launcher=0x7f020013;
        public static final int ic_remove_circle_outline_black_24dp=0x7f020014;
        public static final int ic_setting=0x7f020015;
        public static final int item_bar=0x7f020016;
        public static final int layout_selector=0x7f020017;
        public static final int layout_selector2=0x7f020018;
        public static final int nomalColor=0x7f02002e;
        public static final int octopus=0x7f020019;
        public static final int octopus2=0x7f02001a;
        public static final int octopus3=0x7f02001b;
        public static final int pressColor=0x7f02002f;
        public static final int qingdaobeer=0x7f02001c;
        public static final int remove=0x7f02001d;
        public static final int remove2=0x7f02001e;
        public static final int remove3=0x7f02001f;
        public static final int remove4=0x7f020020;
        public static final int shape_data=0x7f020021;
        public static final int shoppincart=0x7f020022;
        public static final int shoppingcar=0x7f020023;
        public static final int shoppingcar3=0x7f020024;
        public static final int smileface=0x7f020025;
        public static final int smileface2=0x7f020026;
        public static final int smilface2=0x7f020027;
        public static final int snowbeer=0x7f020028;
        public static final int stu=0x7f020029;
        public static final int tab_bg2=0x7f02002a;
        public static final int title_bar=0x7f02002b;
        public static final int whiteball=0x7f02002c;
        public static final int xuebi=0x7f02002d;
    }
    public static final class id {
        public static final int AddbeefNoodle=0x7f09002a;
        public static final int Irating=0x7f090043;
        public static final int TableLayout=0x7f090031;
        public static final int action_settings=0x7f090074;
        public static final int addres=0x7f090013;
        public static final int addressEditText=0x7f090014;
        public static final int back=0x7f09005c;
        public static final int beefNoodleDesc=0x7f090028;
        public static final int beefNoodlePrice=0x7f090029;
        public static final int beefNoodleText=0x7f090027;
        public static final int beefNoodleView=0x7f090026;
        public static final int beefNoodle_remove=0x7f09002c;
        public static final int beefnoodle_count=0x7f09002b;
        public static final int buttonLayout=0x7f090022;
        public static final int buttonLayout02=0x7f090024;
        public static final int checkout=0x7f090073;
        public static final int descri=0x7f090015;
        public static final int descriEditText=0x7f090016;
        public static final int diancan=0x7f090004;
        public static final int diancan_text=0x7f090005;
        public static final int div=0x7f090017;
        public static final int eButtonLayout=0x7f090059;
        public static final int eUserName=0x7f090047;
        public static final int eUserNameLayout=0x7f090046;
        public static final int eUserNameText=0x7f090048;
        public static final int enter=0x7f09005a;
        public static final int female=0x7f090050;
        public static final int gender=0x7f09004d;
        public static final int genderGroup=0x7f09004e;
        public static final int genderLayout=0x7f09004c;
        public static final int help=0x7f090033;
        public static final int id_tab_diancan=0x7f090003;
        public static final int id_tab_my=0x7f090009;
        public static final int id_tab_order=0x7f090006;
        public static final int id_tab_waimai=0x7f090000;
        public static final int id_viewpager=0x7f090030;
        public static final int index=0x7f09002d;
        public static final int intro=0x7f09006a;
        public static final int itemCount=0x7f090036;
        public static final int itemName=0x7f090035;
        public static final int itemPrice=0x7f090037;
        public static final int itemlist=0x7f090019;
        public static final int iv_add_cart=0x7f090071;
        public static final int list=0x7f090018;
        public static final int listview_1=0x7f09006f;
        public static final int listview_2=0x7f090070;
        public static final int loginEnroll=0x7f090025;
        public static final int loginLog=0x7f090023;
        public static final int logout=0x7f090034;
        public static final int male=0x7f09004f;
        public static final int mesgButton=0x7f090045;
        public static final int message=0x7f090044;
        public static final int my=0x7f09000a;
        public static final int my_setting=0x7f090032;
        public static final int my_text=0x7f09000b;
        public static final int name=0x7f090067;
        public static final int nameText=0x7f090010;
        public static final int octopus=0x7f090066;
        public static final int order=0x7f090007;
        public static final int orderLayout=0x7f090038;
        public static final int orderListView01=0x7f090042;
        public static final int order_text=0x7f090008;
        public static final int orderbutton=0x7f09001b;
        public static final int orderdetailDelete=0x7f09003f;
        public static final int orderdetailTextView01=0x7f090039;
        public static final int orderdetailTextView02=0x7f09003a;
        public static final int orderdetailTextView03=0x7f09003b;
        public static final int orderdetailTextView04=0x7f09003c;
        public static final int orderdetailTextView05=0x7f09003d;
        public static final int orderdetailTextView06=0x7f09003e;
        public static final int password=0x7f090020;
        public static final int password3=0x7f090054;
        public static final int people=0x7f09000f;
        public static final int phone=0x7f090057;
        public static final int price=0x7f09006b;
        public static final int products=0x7f09006e;
        public static final int pwdLayout=0x7f09001f;
        public static final int pwdLayout02=0x7f090051;
        public static final int pwdLayout03=0x7f090053;
        public static final int pwdText=0x7f090021;
        public static final int pwdText2=0x7f090052;
        public static final int pwdText3=0x7f090055;
        public static final int rankText=0x7f090068;
        public static final int rating=0x7f090069;
        public static final int realName=0x7f09004a;
        public static final int realNameLayout=0x7f090049;
        public static final int realNameText=0x7f09004b;
        public static final int reset=0x7f09005b;
        public static final int shouhuo=0x7f090040;
        public static final int status=0x7f09002f;
        public static final int stupic=0x7f09006d;
        public static final int telLayout=0x7f090056;
        public static final int telText=0x7f090058;
        public static final int teleEditText=0x7f090012;
        public static final int telephone=0x7f090011;
        public static final int textView1=0x7f09006c;
        public static final int time=0x7f09002e;
        public static final int title=0x7f09000e;
        public static final int titles=0x7f090041;
        public static final int totalprice=0x7f09001a;
        public static final int tv_catogray=0x7f09000c;
        public static final int tv_count=0x7f09000d;
        public static final int tv_count_price=0x7f090072;
        public static final int userName=0x7f09001d;
        public static final int userNameLayout=0x7f09001c;
        public static final int userNameText=0x7f09001e;
        public static final int userinfoButton01=0x7f090065;
        public static final int userinfoEditText02=0x7f09005f;
        public static final int userinfoEditText03=0x7f090060;
        public static final int userinfoEditText04=0x7f090064;
        public static final int userinfoLinearLayout02=0x7f09005e;
        public static final int userinfoRadioButton01=0x7f090062;
        public static final int userinfoRadioButton02=0x7f090063;
        public static final int userinfoRadioGroup01=0x7f090061;
        public static final int userinfoTextView01=0x7f09005d;
        public static final int waimai=0x7f090001;
        public static final int waimai_text=0x7f090002;
    }
    public static final class layout {
        public static final int bottom=0x7f030000;
        public static final int catagory_item_list=0x7f030001;
        public static final int checkout=0x7f030002;
        public static final int enroll=0x7f030003;
        public static final int goods_item_list=0x7f030004;
        public static final int help=0x7f030005;
        public static final int items=0x7f030006;
        public static final int main_activity=0x7f030007;
        public static final int my=0x7f030008;
        public static final int order_item_list=0x7f030009;
        public static final int orderdetail=0x7f03000a;
        public static final int orderinfo=0x7f03000b;
        public static final int orders=0x7f03000c;
        public static final int rank=0x7f03000d;
        public static final int register=0x7f03000e;
        public static final int setting=0x7f03000f;
        public static final int tab01=0x7f030010;
        public static final int tab02=0x7f030011;
        public static final int top=0x7f030012;
        public static final int waimai=0x7f030013;
    }
    public static final class menu {
        public static final int main=0x7f080000;
    }
    public static final class string {
        public static final int action_settings=0x7f060001;
        public static final int address=0x7f06000f;
        public static final int app_name=0x7f060000;
        public static final int back=0x7f060012;
        public static final int beefNoodle=0x7f06001b;
        public static final int beefRiceFlour=0x7f06001c;
        public static final int beefSoup=0x7f06001d;
        public static final int checkout=0x7f060021;
        public static final int clear=0x7f060004;
        public static final int cole=0x7f06001e;
        public static final int diancan=0x7f060023;
        public static final int enroll=0x7f060005;
        public static final int enter=0x7f060010;
        public static final int female=0x7f06000c;
        public static final int gender=0x7f06000b;
        public static final int hello_world=0x7f060002;
        public static final int help=0x7f060019;
        public static final int login=0x7f060003;
        public static final int logout=0x7f060018;
        public static final int male=0x7f06000d;
        public static final int my=0x7f060025;
        public static final int order=0x7f060024;
        public static final int orderdetail=0x7f060017;
        public static final int password=0x7f060009;
        public static final int password2=0x7f06000a;
        public static final int presscolor=0x7f060026;
        public static final int pwdhint=0x7f060013;
        public static final int pwdhint2=0x7f060014;
        public static final int quit=0x7f060006;
        public static final int realname=0x7f060008;
        public static final int reset=0x7f060011;
        public static final int rnhint=0x7f060016;
        public static final int setting=0x7f06001a;
        public static final int snowbeer=0x7f060020;
        public static final int telehint=0x7f060015;
        public static final int telephone=0x7f06000e;
        public static final int userName=0x7f060007;
        public static final int waimai=0x7f060022;
        public static final int xuebi=0x7f06001f;
    }
    public static final class style {
        /** 
        Base application theme, dependent on API level. This theme is replaced
        by AppBaseTheme from res/values-vXX/styles.xml on newer devices.
    

            Theme customizations available in newer API levels can go in
            res/values-vXX/styles.xml, while customizations related to
            backward-compatibility can go here.
        

        Base application theme for API 11+. This theme completely replaces
        AppBaseTheme from res/values/styles.xml on API 11+ devices.
    
 API 11 theme customizations can go here. 

        Base application theme for API 14+. This theme completely replaces
        AppBaseTheme from BOTH res/values/styles.xml and
        res/values-v11/styles.xml on API 14+ devices.
    
 API 14 theme customizations can go here. 
         */
        public static final int AppBaseTheme=0x7f070000;
        /**  Application theme. 
 All customizations that are NOT specific to a particular API-level can go here. 
         */
        public static final int AppTheme=0x7f070001;
    }
}
